// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldhzvzxmnshpboocnpiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaHp2enhtbnNocGJvb2NucGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjQ1NzYsImV4cCI6MjA3NDU0MDU3Nn0.FR-fWoLFwmRehDZ-06u3mkVNoVg0nO6LiBzd3tqOuAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true, // Always persist sessions
    autoRefreshToken: true, // Auto-refresh tokens to maintain session
    detectSessionInUrl: false, // Don't detect sessions from URL
  }
});